// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PSUPARAMS_APSU_FBS_H_
#define FLATBUFFERS_GENERATED_PSUPARAMS_APSU_FBS_H_

#include "flatbuffers/flatbuffers.h"

namespace apsu {
namespace fbs {

struct ItemParams;

struct TableParams;

struct QueryParams;
struct QueryParamsBuilder;

struct SEALParams;
struct SEALParamsBuilder;

struct PSUParams;
struct PSUParamsBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) ItemParams FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t felts_per_item_;

 public:
  ItemParams()
      : felts_per_item_(0) {
  }
  ItemParams(uint32_t _felts_per_item)
      : felts_per_item_(flatbuffers::EndianScalar(_felts_per_item)) {
  }
  uint32_t felts_per_item() const {
    return flatbuffers::EndianScalar(felts_per_item_);
  }
};
FLATBUFFERS_STRUCT_END(ItemParams, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) TableParams FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t table_size_;
  uint32_t max_items_per_bin_;
  uint32_t hash_func_count_;

 public:
  TableParams()
      : table_size_(0),
        max_items_per_bin_(0),
        hash_func_count_(0) {
  }
  TableParams(uint32_t _table_size, uint32_t _max_items_per_bin, uint32_t _hash_func_count)
      : table_size_(flatbuffers::EndianScalar(_table_size)),
        max_items_per_bin_(flatbuffers::EndianScalar(_max_items_per_bin)),
        hash_func_count_(flatbuffers::EndianScalar(_hash_func_count)) {
  }
  uint32_t table_size() const {
    return flatbuffers::EndianScalar(table_size_);
  }
  uint32_t max_items_per_bin() const {
    return flatbuffers::EndianScalar(max_items_per_bin_);
  }
  uint32_t hash_func_count() const {
    return flatbuffers::EndianScalar(hash_func_count_);
  }
};
FLATBUFFERS_STRUCT_END(TableParams, 12);

struct QueryParams FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef QueryParamsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PS_LOW_DEGREE = 4,
    VT_QUERY_POWERS = 6
  };
  uint32_t ps_low_degree() const {
    return GetField<uint32_t>(VT_PS_LOW_DEGREE, 0);
  }
  const flatbuffers::Vector<uint32_t> *query_powers() const {
    return GetPointer<const flatbuffers::Vector<uint32_t> *>(VT_QUERY_POWERS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PS_LOW_DEGREE, 4) &&
           VerifyOffset(verifier, VT_QUERY_POWERS) &&
           verifier.VerifyVector(query_powers()) &&
           verifier.EndTable();
  }
};

struct QueryParamsBuilder {
  typedef QueryParams Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_ps_low_degree(uint32_t ps_low_degree) {
    fbb_.AddElement<uint32_t>(QueryParams::VT_PS_LOW_DEGREE, ps_low_degree, 0);
  }
  void add_query_powers(flatbuffers::Offset<flatbuffers::Vector<uint32_t>> query_powers) {
    fbb_.AddOffset(QueryParams::VT_QUERY_POWERS, query_powers);
  }
  explicit QueryParamsBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<QueryParams> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<QueryParams>(end);
    return o;
  }
};

inline flatbuffers::Offset<QueryParams> CreateQueryParams(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ps_low_degree = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint32_t>> query_powers = 0) {
  QueryParamsBuilder builder_(_fbb);
  builder_.add_query_powers(query_powers);
  builder_.add_ps_low_degree(ps_low_degree);
  return builder_.Finish();
}

inline flatbuffers::Offset<QueryParams> CreateQueryParamsDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ps_low_degree = 0,
    const std::vector<uint32_t> *query_powers = nullptr) {
  auto query_powers__ = query_powers ? _fbb.CreateVector<uint32_t>(*query_powers) : 0;
  return apsu::fbs::CreateQueryParams(
      _fbb,
      ps_low_degree,
      query_powers__);
}

struct SEALParams FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SEALParamsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4
  };
  const flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
};

struct SEALParamsBuilder {
  typedef SEALParams Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_data(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(SEALParams::VT_DATA, data);
  }
  explicit SEALParamsBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<SEALParams> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SEALParams>(end);
    fbb_.Required(o, SEALParams::VT_DATA);
    return o;
  }
};

inline flatbuffers::Offset<SEALParams> CreateSEALParams(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> data = 0) {
  SEALParamsBuilder builder_(_fbb);
  builder_.add_data(data);
  return builder_.Finish();
}

inline flatbuffers::Offset<SEALParams> CreateSEALParamsDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return apsu::fbs::CreateSEALParams(
      _fbb,
      data__);
}

struct PSUParams FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PSUParamsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_ITEM_PARAMS = 6,
    VT_TABLE_PARAMS = 8,
    VT_QUERY_PARAMS = 10,
    VT_SEAL_PARAMS = 12
  };
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  const apsu::fbs::ItemParams *item_params() const {
    return GetStruct<const apsu::fbs::ItemParams *>(VT_ITEM_PARAMS);
  }
  const apsu::fbs::TableParams *table_params() const {
    return GetStruct<const apsu::fbs::TableParams *>(VT_TABLE_PARAMS);
  }
  const apsu::fbs::QueryParams *query_params() const {
    return GetPointer<const apsu::fbs::QueryParams *>(VT_QUERY_PARAMS);
  }
  const apsu::fbs::SEALParams *seal_params() const {
    return GetPointer<const apsu::fbs::SEALParams *>(VT_SEAL_PARAMS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyField<apsu::fbs::ItemParams>(verifier, VT_ITEM_PARAMS, 4) &&
           VerifyField<apsu::fbs::TableParams>(verifier, VT_TABLE_PARAMS, 4) &&
           VerifyOffset(verifier, VT_QUERY_PARAMS) &&
           verifier.VerifyTable(query_params()) &&
           VerifyOffsetRequired(verifier, VT_SEAL_PARAMS) &&
           verifier.VerifyTable(seal_params()) &&
           verifier.EndTable();
  }
};

struct PSUParamsBuilder {
  typedef PSUParams Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(PSUParams::VT_VERSION, version, 0);
  }
  void add_item_params(const apsu::fbs::ItemParams *item_params) {
    fbb_.AddStruct(PSUParams::VT_ITEM_PARAMS, item_params);
  }
  void add_table_params(const apsu::fbs::TableParams *table_params) {
    fbb_.AddStruct(PSUParams::VT_TABLE_PARAMS, table_params);
  }
  void add_query_params(flatbuffers::Offset<apsu::fbs::QueryParams> query_params) {
    fbb_.AddOffset(PSUParams::VT_QUERY_PARAMS, query_params);
  }
  void add_seal_params(flatbuffers::Offset<apsu::fbs::SEALParams> seal_params) {
    fbb_.AddOffset(PSUParams::VT_SEAL_PARAMS, seal_params);
  }
  explicit PSUParamsBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<PSUParams> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PSUParams>(end);
    fbb_.Required(o, PSUParams::VT_SEAL_PARAMS);
    return o;
  }
};

inline flatbuffers::Offset<PSUParams> CreatePSUParams(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 0,
    const apsu::fbs::ItemParams *item_params = nullptr,
    const apsu::fbs::TableParams *table_params = nullptr,
    flatbuffers::Offset<apsu::fbs::QueryParams> query_params = 0,
    flatbuffers::Offset<apsu::fbs::SEALParams> seal_params = 0) {
  PSUParamsBuilder builder_(_fbb);
  builder_.add_seal_params(seal_params);
  builder_.add_query_params(query_params);
  builder_.add_table_params(table_params);
  builder_.add_item_params(item_params);
  builder_.add_version(version);
  return builder_.Finish();
}

inline const apsu::fbs::PSUParams *GetPSUParams(const void *buf) {
  return flatbuffers::GetRoot<apsu::fbs::PSUParams>(buf);
}

inline const apsu::fbs::PSUParams *GetSizePrefixedPSUParams(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<apsu::fbs::PSUParams>(buf);
}

inline bool VerifyPSUParamsBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<apsu::fbs::PSUParams>(nullptr);
}

inline bool VerifySizePrefixedPSUParamsBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<apsu::fbs::PSUParams>(nullptr);
}

inline void FinishPSUParamsBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<apsu::fbs::PSUParams> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPSUParamsBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<apsu::fbs::PSUParams> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fbs
}  // namespace apsu

#endif  // FLATBUFFERS_GENERATED_PSUPARAMS_APSU_FBS_H_
